<a href="https://colab.research.google.com/github/sazzad15-1779/machine-learning/blob/master/all_supervised_machine_learning_algorithm_apply_in_one_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

In [250]:
data = pd.read_csv('https://raw.githubusercontent.com/shivang98/Social-Network-ads-Boost/master/Social_Network_Ads.csv')
data.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

# dummi values by Labelencoder

In [251]:
from sklearn.preprocessing  import LabelEncoder
l = LabelEncoder()
data['Gender']=l.fit_transform(data['Gender'])
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

# real_x,real_y

In [0]:
x = data.drop(['User ID','Purchased'],axis=1)
y = data['Purchased']


## split real data

In [0]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y= train_test_split(x,y,test_size =.25,random_state=10)

## standarscaler

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_x=scaler.fit_transform(train_x)
test_x=scaler.fit_transform(test_x)

## KNN apply

In [255]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=15,metric = 'minkowski')
knn.fit(train_x,train_y)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')

In [256]:
knn.predict(test_x)

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [257]:
np.array(test_y)

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [258]:
knn.score(test_x,test_y)

0.92

In [259]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,knn.predict(test_x)) 

array([[63,  6],
       [ 2, 29]])

# random forest apply

In [260]:
from sklearn.ensemble import RandomForestClassifier
random = RandomForestClassifier(n_estimators=10,random_state=1)
random.fit(train_x,train_y)

 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [261]:
random.predict(test_x)

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [262]:
np.array(test_y)

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [263]:
random.score(test_x,test_y)

0.93

In [264]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,random.predict(test_x)) 

array([[63,  6],
       [ 1, 30]])

# decision tree apply

In [265]:
from sklearn.tree import DecisionTreeRegressor
dec = DecisionTreeRegressor(random_state=1)
dec.fit(train_x,train_y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [266]:
dec.predict(test_x)

array([0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0.])

In [267]:
dec.score(test_x,test_y)

0.579242636746143

In [268]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,dec.predict(test_x)) 

array([[61,  8],
       [ 1, 30]])

# supported vector machine (svm)

In [269]:
from sklearn.svm import SVC
svm = SVC(random_state=0,kernel = 'linear')
svm.fit(train_x,train_y)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [270]:
svm.predict(test_x)

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [271]:
svm.score(test_x,test_y)

0.9

In [272]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,svm.predict(test_x)) 

array([[64,  5],
       [ 5, 26]])

## Linear Regression apply

In [274]:
from sklearn.linear_model import LinearRegression
l_reg = LinearRegression()
l_reg.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [275]:
l_reg.predict(test_x)

array([ 0.49204786,  0.34638006,  0.5513621 ,  0.50986493, -0.10751041,
        0.69923942,  0.32294317,  0.53403558,  0.28696771,  0.3981593 ,
        0.44230541,  0.24844141,  1.19057696,  0.68527621,  0.42863655,
        0.41234221,  0.17698105, -0.00179355, -0.01740109,  0.64098085,
        0.01990089, -0.0238058 ,  0.40235448,  0.98353464,  0.79465072,
        0.32284506,  0.36463656,  0.64454038,  0.52017049,  0.20949508,
        0.13192435,  0.13916502,  0.17158094,  0.52618275,  0.82198846,
        0.15739803,  0.68704216,  0.70630735,  0.36871015,  0.06566786,
        0.38664882,  0.45013476, -0.15683691,  0.11776492,  0.28868668,
        0.12387529,  0.88162052,  0.32294317,  0.3821593 ,  0.00596117,
        0.36017053,  0.53914135,  0.52179135,  0.3426243 ,  0.40426967,
        0.41030542,  0.74677233,  0.14142152,  0.60353378,  1.24225808,
        0.13938473,  0.73055262,  0.3328328 ,  0.67666197,  1.06692142,
        0.6253733 ,  0.49204786,  1.12483452, -0.28456603,  0.40

In [276]:
l_reg.score(test_x,test_y)

0.46949857167175635

# logistic regression

In [278]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(train_x,train_y) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [280]:
log_reg.predict(test_x)

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [281]:
log_reg.score(test_x,test_y)

0.9

In [282]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,log_reg.predict(test_x)) 

array([[64,  5],
       [ 5, 26]])

# polynomial regression


In [0]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=3)
x_poly =poly_reg.fit_transform(train_x)
x_test = poly_reg.fit_transform(test_x)

In [289]:
linear_poly_reg = LinearRegression()
linear_poly_reg.fit(x_poly,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
linear_poly_reg.predict(x_test)

In [291]:
linear_poly_reg.score(x_test,test_y)

-8.170401045569122e+23

# lasso regression

In [294]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(random_state=0)
lasso_reg.fit(train_x,train_y)


Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=0,
      selection='cyclic', tol=0.0001, warm_start=False)

In [296]:
lasso_reg.predict(test_x)

array([0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333

In [297]:
lasso_reg.score(test_x,test_y)

-0.018752272609215748

# Ridge regression

In [301]:
from sklearn.linear_model import Ridge
rid_reg =Ridge(random_state=0)
rid_reg.fit(train_x,train_y)


Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=0, solver='auto', tol=0.001)

In [302]:
rid_reg.predict(test_x)

array([ 4.91589871e-01,  3.46552103e-01,  5.50951800e-01,  5.09427719e-01,
       -1.05978368e-01,  6.98110526e-01,  3.22938508e-01,  5.33362554e-01,
        2.87140454e-01,  3.98166487e-01,  4.41983604e-01,  2.49099085e-01,
        1.18813544e+00,  6.84202872e-01,  4.28225111e-01,  4.12160180e-01,
        1.77751579e-01, -7.05166634e-04, -1.64220560e-02,  6.40259511e-01,
        2.10494735e-02, -2.25955660e-02,  4.02219038e-01,  9.81741033e-01,
        7.93306828e-01,  3.22888787e-01,  3.64562029e-01,  6.44040544e-01,
        5.19504620e-01,  2.09818320e-01,  1.32446465e-01,  1.40044850e-01,
        1.72061870e-01,  5.25479249e-01,  8.20823814e-01,  1.58068177e-01,
        6.86048426e-01,  7.05596069e-01,  3.68578262e-01,  6.66892279e-02,
        3.86452429e-01,  4.49880311e-01, -1.55399156e-01,  1.18439370e-01,
        2.89012811e-01,  1.24463720e-01,  8.80321502e-01,  3.22938508e-01,
        3.82250716e-01,  7.12841789e-03,  3.60346915e-01,  5.38903102e-01,
        5.21327257e-01,  

In [303]:
rid_reg.score(test_x,test_y)

0.46952080199577556

# elastic net regression

In [306]:
from sklearn.linear_model import ElasticNet
elastic_reg =ElasticNet(random_state=0)
elastic_reg.fit(train_x,train_y) 

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [307]:
elastic_reg.predict(test_x)

array([0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333333,
       0.37333333, 0.37333333, 0.37333333, 0.37333333, 0.37333

In [308]:
elastic_reg.score(test_x,test_y)

-0.018752272609215748