<a href="https://colab.research.google.com/github/sazzad15-1779/machine-learning/blob/master/Naive_Bayes_classification_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## import library

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

# loading data

In [137]:
data = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv')
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

# data wrangling 

In [138]:
data['spam']= data['Category'].apply(lambda x:1 if x == 'spam' else 0)
data.drop('Category',inplace=True,axis=1)
data.head()

Message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

## input axis

In [0]:
x= data['Message']
y= data['spam']

# vectorizing sentece 

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x = v.fit_transform(x)

# train,test split 

In [0]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=.1,random_state=1)

# fit naive bayes model =>> multinomial version

In [142]:
from sklearn.naive_bayes import MultinomialNB
naive = MultinomialNB()
naive.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [143]:
test_x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# prediction

In [144]:
naive.predict(test_x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [145]:
print('      0 probability___| '+'|___1 probability \n')
naive.predict_proba(test_x)

      0 probability___| |___1 probability 



array([[9.94011140e-01, 5.98886049e-03],
       [9.99988791e-01, 1.12092860e-05],
       [9.95449448e-01, 4.55055225e-03],
       ...,
       [9.98187542e-01, 1.81245848e-03],
       [9.91785592e-01, 8.21440832e-03],
       [9.99410868e-01, 5.89132283e-04]])

# accuracy check 

In [146]:
naive.score(test_x,test_y)

0.9910394265232975

In [147]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,naive.predict(test_x))

array([[485,   4],
       [  1,  68]])

In [148]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,naive.predict(test_x))

0.9910394265232975

In [149]:
from sklearn.metrics import classification_report
classification_report(test_y,naive.predict(test_x))

'              precision    recall  f1-score   support\n\n           0       1.00      0.99      0.99       489\n           1       0.94      0.99      0.96        69\n\n    accuracy                           0.99       558\n   macro avg       0.97      0.99      0.98       558\nweighted avg       0.99      0.99      0.99       558\n'

In [150]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(test_y,naive.predict(test_x))

(array([0.99794239, 0.94444444]),
 array([0.99182004, 0.98550725]),
 array([0.99487179, 0.96453901]),
 array([489,  69]))